# Version of docker-compose to use 
version: "3"

services:
  app: # This is the service for the Django application
    build:
      context: . # Sets the directory containing a Dockerfile .

    # Maps port on the local machine to port on Docker image
    ports:
      - "8080:8080"
      
    volumes: 
    # Copy changes made to the project to your image working directory as changes are made.
      - .:/django-docker-okteto
    
    environment:
      # The environment variable credentials that is needed 
      # in django settings for Postgres to work.
      - DB_HOST=pg
      - DB_NAME=app2
      - DB_USER=postgres3
      - DB_PASS=supersecretpassword
    depends_on:
      - pg

  pg:
    image: postgres:10-alpine # pulling Postgres image from Docker hub
    environment:
      # credentials required by postgres image
      - POSTGRES_DB=app2
      - POSTGRES_USER=postgres3
      - POSTGRES_PASSWORD=supersecretpassword