version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000  
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ayomi
      - POSTGRES_USER=ayomi
      - POSTGRES_PASSWORD=youcanconnect 